name: Build Windows Executable

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Update from v3
      
    - name: Set up Python
      uses: actions/setup-python@v5  # Update from v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # tkinter is included in Windows Python installations
        pip install pyinstaller
        
    - name: Test tkinter availability
      run: |
        python -c "import tkinter; print('tkinter version:', tkinter.TkVersion)"
        
    - name: Build executable
      run: |
        pyinstaller --onefile --noconsole --name PomodoroFlashTimer --icon=./resources/pomodoro.ico pomodoroFlashTimer.py
      
    - name: Debug Info
      run: |
        echo "Current directory: $(Get-Location)"
        echo "Files in dist directory:"
        if (Test-Path -Path dist) {
            Get-ChildItem -Path dist -Force
        } else {
            echo "dist directory does not exist"
        }
        echo "Current user: $env:USERNAME"
        echo "GitHub ref: $env:GITHUB_REF"
      
    - name: Create release package
      run: |
        mkdir -p release
        copy -Path "dist\PomodoroFlashTimer.exe" -Destination "release\"
        copy README.md release\
        
    - name: Get tag version
      id: get_version
      run: |
        if [[ "$GITHUB_REF" == refs/tags/* ]]; then
          # This is a tag-based trigger
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "IS_RELEASE=true" >> $GITHUB_OUTPUT
        else
          # This is a manual trigger
          echo "VERSION=dev-$(date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT
          echo "IS_RELEASE=false" >> $GITHUB_OUTPUT
        fi
      shell: bash
      
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      if: steps.get_version.outputs.IS_RELEASE == 'true'
      with:
        files: |
          release/PomodoroFlashTimer.exe
          release/README.md
        name: Pomodoro Flash Timer ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false
        body: |
          # Pomodoro Flash Timer ${{ steps.get_version.outputs.VERSION }}

          ## Platform
            - Windows
                      
          ## Installation
          - Download and run the executable
          - No installation required
          
          ## Usage
          - Run the application
          - Enter work and break times when prompted
          - Timer will appear in the bottom-left corner of your screen
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload build artifact
      uses: actions/upload-artifact@v4  # Changed from v3 to v4
      if: steps.get_version.outputs.IS_RELEASE == 'false'
      with:
        name: PomodoroFlashTimer-${{ steps.get_version.outputs.VERSION }}
        path: release/
        retention-days: 7