name: Build macOS Executable

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install required dependencies including Pillow
        pip install pyinstaller pillow
        
        # Ensure tkinter is available on macOS
        # Python from actions/setup-python should include tkinter
        # but we'll install it via brew as a fallback
        if ! python -c "import tkinter" &> /dev/null; then
          echo "Tkinter not found in Python installation, installing via brew..."
          brew install python-tk@3.10
        fi
        
        
    - name: Verify dependencies
      run: |
        # Verify tkinter
        python -c "import tkinter; print('tkinter version:', tkinter.TkVersion)"
        
        # Verify PIL
        python -c "from PIL import Image; print('Pillow version:', Image.__version__)"
        
    - name: Build executable with macOS icon
      run: |
        pyinstaller --onefile --windowed --name PomodoroFlashTimer --icon=./resources/pomodoro.icns pomodoroFlashTimer.py
      
    - name: Debug Info
      run: |
        echo "Current directory: $(pwd)"
        echo "Files in dist directory:"
        if [ -d "dist" ]; then
          ls -la dist
        else
          echo "dist directory does not exist"
        fi
        echo "Current user: $(whoami)"
        echo "GitHub ref: $GITHUB_REF"
        # Check for app bundle structure
        find dist -type f | sort
      
    - name: Create release package
      run: |
        mkdir -p release
        # Copy the executable
        if [ -d "dist/PomodoroFlashTimer.app" ]; then
          # If it's a macOS app bundle
          cp -R dist/PomodoroFlashTimer.app release/
        else
          # If it's a standard executable
          cp dist/PomodoroFlashTimer release/
          chmod +x release/PomodoroFlashTimer
        fi
        cp README.md release/
        
    - name: Get tag version
      id: get_version
      run: |
        if [[ "$GITHUB_REF" == refs/tags/* ]]; then
          # This is a tag-based trigger
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "IS_RELEASE=true" >> $GITHUB_OUTPUT
        else
          # This is a manual trigger
          echo "VERSION=dev-$(date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT
          echo "IS_RELEASE=false" >> $GITHUB_OUTPUT
        fi
      
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      if: steps.get_version.outputs.IS_RELEASE == 'true'
      with:
        files: |
          release/*
        name: Pomodoro Flash Timer ${{ steps.get_version.outputs.VERSION }} (macOS)
        draft: false
        prerelease: false
        body: |
          # Pomodoro Flash Timer ${{ steps.get_version.outputs.VERSION }} for macOS
          
          ## Installation
          - Download the executable
          - You may need to right-click and choose "Open" to bypass Gatekeeper
          - No installation required
          
          ## Usage
          - Run the application
          - Enter work and break times when prompted
          - Timer will appear in the bottom-left corner of your screen
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      if: steps.get_version.outputs.IS_RELEASE == 'false'
      with:
        name: PomodoroFlashTimer-macOS-${{ steps.get_version.outputs.VERSION }}
        path: release/
        retention-days: 7