name: Build Windows Executable

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # tkinter is included in Windows Python installations
        pip install pyinstaller
        
    - name: Test tkinter availability
      run: |
        python -c "import tkinter; print('tkinter version:', tkinter.TkVersion)"
        
    - name: Build executable
      run: |
        pyinstaller --onefile --noconsole --name PomodoroFlashTimer --icon=./resources/pomodoro.ico pomodoroFlashTimer.py
      
    - name: Debug Info
      run: |
        echo "Current directory: $(Get-Location)"
        echo "Files in dist directory:"
        if (Test-Path -Path dist) {
            Get-ChildItem -Path dist -Force
        } else {
            echo "dist directory does not exist"
        }
        echo "Current user: $env:USERNAME"
        echo "GitHub ref: $env:GITHUB_REF"
        if ($LASTEXITCODE -ne 0) {
            echo "Command failed!"
            exit 1
        }
      
    - name: Create release package
      run: |
        mkdir -p release
        copy -Path "dist\PomodoroFlashTimer.exe" -Destination "release\"
        copy README.md release\
        
    - name: Get tag version
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      shell: bash
      
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release/PomodoroFlashTimer.exe
          release/README.md
        name: Pomodoro Flash Timer ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false
        body: |
          # Pomodoro Flash Timer ${{ steps.get_version.outputs.VERSION }}
          
          ## Installation
          - Download and run the executable
          - No installation required
          
          ## Usage
          - Run the application
          - Enter work and break times when prompted
          - Timer will appear in the bottom-left corner of your screen
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}