name: Pylint

on: [push, pull_request]  # Also run on PRs

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]  # Focus on your target version
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        # Install your project dependencies if needed for proper checking
        # pip install -r requirements.txt
        
    - name: Install tkinter
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk
        
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
